app:
  name: demo
  role: test
  descriptions: 测试用例
  cluster-name: moses
  project: moses-demos
  datasource:
    username: root
    name: demo-chun
    port: 3306
    password: KLHTJZxEEdam3bf+QI8MWT5GwbsUtSkZJ76rtOFl8i8a4xw6M/GXk0iCy+W8loFd0tyjbzyRLINo9wtujXWz1w==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK1VN+B85BXf7NLy0otwG3iDaD7UTs/P1X9UGHfEik2vqQWknWmdwMS3woGUUN+yC0QxsghZLAWaheYq61KLQUCAwEAAQ==


spring:
  datasource:
    druid:
      max-active: 100
  profiles:
    include:
    - web
    - mybatis

mybatis:
  #config-location : "classpath:mybatis-config.xml"
  mapper-locations : "classpath:mapper/*Mapper.xml"
logging:
  level:
    org.springframework: Info
    cn.vpclub.moses: info
    org.jgroups: info

