app:
  name: demo
  role: test
  descriptions: 测试用例
  cluster-name: moses
  project: moses-demos
  datasource:
    username: root
    name: demo-chun
    port: 3306
    password: KLHTJZxEEdam3
    druid:
      public-key: MFwwDQYJKoZIhv


spring:
  datasource:
    druid:
      max-active: 100
  profiles:
    include:
    - web
    - mybatis

mybatis:
  #config-location : "classpath:mybatis-config.xml"
  mapper-locations : "classpath:mapper/*Mapper.xml"
logging:
  level:
    org.springframework: Info
    cn.vpclub.moses: info
    org.jgroups: info

